GET http://localhost:3000/users

###

POST  http://localhost:3000/users
Content-Type: application/json


{
    "id":"2",
    "accountName":"Player2",
    "accountImageUrl":"assets/player2.png",
    "accountLevel":1,
    "accountExperience":0
}